---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: es
  name: elasticsearch
  namespace: elk
spec:
  ports:
    - name: http
      port: 9200
      protocol: TCP
      targetPort: 9200
      nodePort: 39200
    - name: tcp
      port: 9300
      protocol: TCP
      targetPort: 9300
      nodePort: 39300
  selector:
    app: es
  sessionAffinity: None
  type: NodePort

