---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elk
spec:
  ports:
    - name: http
      nodePort: 31487
      port: 5601
      protocol: TCP
      targetPort: 5601
  selector:
    app: kibana
  type: NodePort

---
---
apiVersion: v1
data:
  kibana.yml: |-
    server.host: 0.0.0.0
    elasticsearch:
      hosts: ${ELASTICSEARCH_HOSTS}
      username: 'elastic'
      password: 'QXsGQsl!LyerIF2c'
    kibana.index: ".kibana"
    i18n.locale: "zh-CN"
kind: ConfigMap
metadata:
  labels:
    app: kibana
  name: kibana-config
  namespace: elk

